info:
  description: Swagger schema for Nextflow server
  title: nf-server
  version: 1.0.0
security:
  - APIKeyHeader: []
paths:

  /ping:
    get:
      tags:
      - ping
      summary: checks whether Nextflow is running on the server
      operationId: pingNextflowServer
      responses:
        "200":
          description: Server is up and running
          schema:
            $ref: "#/definitions/error"
        "503":
          description: Nextflow is not running on the server
          schema:
            $ref: "#/definitions/error"

  /jobs:
    post:
      tags:
      - submit
      operationId: submitWorkflow
      parameters:
      - in: "body"
        name: "body"
        description: "Submit a job"
        schema:
          $ref: "#/definitions/job_request"
      responses:
        "202":
          description: Workflow accepted for processing successfully
          schema:
            type: object
            required:
            - job_id
            properties:
              job_id:
                type: string
        "401":
          $ref: "#/responses/UnauthorizedError"
        default:
          description: generic error response
          schema:
            $ref: "#/definitions/error"
        "422":
          description: Workflow was not accepted for processing
          schema:
            $ref: "#/definitions/error"

  /jobs/{job_id}:
    get:
      tags:
      - job
      summary: checks workflow status
      operationId: getJob
      parameters:
      - name: job_id
        in: path
        type: string
        required: true
      responses:
        "200":
          description: Successful operation
          schema:
            type: object
            required:
              - status
            properties:
              status:
                type: string
              error_code:
                type: integer
        "401":
          $ref: "#/responses/UnauthorizedError"
        default:
          description: generic error response
          schema:
            $ref: "#/definitions/error"
    delete:
      tags:
        - job
        summary: deletes a job
        operationId: deleteJob
        parameters:
          - name: job_id
            in: path
            type: string
            required: true
        responses:
          "200":
            description: Successful operation
            schema:
              type: object
              required:
                - status
              properties:
                status:
                  type: string
          "401":
            $ref: "#/responses/UnauthorizedError"
          default:
            description: generic error response
            schema:
              $ref: "#/definitions/error"
schemes:
- http
- https
swagger: "2.0"
definitions:

  job_request:
    type: object
    required:
    - workflow
    properties:
      workflow:
        type: string
      wf_params:
        type: object

  error:
    type: object
    required:
    - message
    properties:
      code:
        type: integer
        format: int64
      message:
        type: string
securityDefinitions:
   APIKeyHeader:
     type: apiKey
     in: header
     name: X-API-Key
responses:
  UnauthorizedError:
    description: API key is missing or invalid
    headers:
      WWW_Authenticate:
        type: string
