apiVersion: v1
kind: PersistentVolume
metadata:
  name: nf-server-pv
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Delete
  glusterfs:
    endpoints: glusterfs
    path: gluster
    readOnly: false
