apiVersion: v1
kind: Service
metadata:
  name: nf-server
  labels:
    app: nf-server
spec:
  type: NodePort
  ports:
  - port: 9005
    targetPort: nf-server
  selector:
    app: nf-server
---
apiVersion: v1
kind: Service
metadata:
  name: flower
  labels:
    app: flower
spec:
  type: NodePort
  ports:
  - port: 8888
    targetPort: flower
  selector:
    app: flower
