version: '3.4'

services:

  jenkins :
    image: redis
    healthcheck:
      test: ["CMD-SHELL", "redis-cli -h $$(hostname) ping"]
      interval: 30s
      timeout: 30s
      retries: 3

  nf-server:
    image: nf-server
    environment:
    - CELERY_BROKER_URL=redis://redis:6379/0
    - CELERY_RESULT_BACKEND=redis://redis:6379/0
    - JENKINS_HOST=http://localhost:8080
    - JENKINS_USER=admin
    - JENKINS_PASSWORD=117a4e6d7744a4a748f251872046b1f161
    - NEXTFLOW_JOB_NAME=bash
    depends_on:
    - redis
    ports:
      - 9005:8000
      
  worker:
    image: nf-server
    environment:
    - CELERY_BROKER_URL=redis://redis:6379/0
    - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
    - redis
    command: ["celery", "-A", "nf_server.celery_app:celery_app", "worker", "-l", "info"]
