version: '3.4'

services:

  nf-server:
    environment:
    - WDB_SOCKET_SERVER=wdb
    - WDB_NO_BROWSER_AUTO_OPEN=True

  flower:
    ports:
    - 7888:8888

  wdb:
    image: kozea/wdb
    ports:
    - "2984:1984"
